//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_rentals
    {
        public int id { get; set; }
        public string customer_name { get; set; }
        public Nullable<System.DateTime> date_rented { get; set; }
        public Nullable<System.DateTime> date_returned { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> car_type_id { get; set; }
    
        public virtual car_types car_types { get; set; }
    }
}
